/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entities.Agenda;
import entities.Compromisso;
import entities.Usuario;
import enums.TipoStatus;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import services.AgendaService;
import services.CompromissoService;

/**
 *
 * @author rebec
 */
public class CompromissoWindow extends javax.swing.JFrame {

    private Agenda agenda;
    private Usuario usuario;
    private Compromisso compromisso;
    private PanelWindow panel;

    public CompromissoWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * Creates new form CriarAgendaWindow
     *
     * @param usuario
     * @param panel
     */
    public CompromissoWindow(Usuario usuario, PanelWindow panel) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        this.panel = panel;
    }

    public CompromissoWindow(Usuario usuario, Agenda agenda) {
        initComponents();
        setLocationRelativeTo(null);
        this.agenda = agenda;
        this.usuario = usuario;
        // this.inputStatus.setSelectedItem(agenda.getStatus().toString());
    }

    public CompromissoWindow(Usuario usuario, Agenda agenda, PanelWindow panel) {
        initComponents();
        setLocationRelativeTo(null);
        this.agenda = agenda;
        this.panel = panel;
        this.usuario = usuario;
        // this.inputStatus.setSelectedItem(agenda.getStatus().toString());
    }

    public CompromissoWindow(Usuario usuario, Agenda agenda, Compromisso compromisso, PanelWindow panel) {
        initComponents();
        setLocationRelativeTo(null);
        this.agenda = agenda;
        this.panel = panel;
        this.usuario = usuario;
        this.compromisso = compromisso;

        lblCriarAgenda.setText("Editar compromisso");
        btnCadastrar.setText("Editar compromisso");

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");

        this.inputNome5.setText(compromisso.getTitulo());
        this.inputDescricao.setText(compromisso.getDescricao());
        this.inputLocal.setText(compromisso.getLocal());
        this.inputHoraInicio.setText(timeFormat.format(compromisso.getDataInicio()));
        this.inputHoraFim.setText(timeFormat.format(compromisso.getDataFim()));
        this.inputDataInicio.setText(dateFormat.format(compromisso.getDataInicio()));
        this.inputDataFim.setText(dateFormat.format(compromisso.getDataFim()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lblCriarAgenda = new javax.swing.JLabel();
                lblNome = new javax.swing.JLabel();
                lblDescricao = new javax.swing.JLabel();
                btnCadastrar = new javax.swing.JButton();
                btnVoltar = new javax.swing.JButton();
                inputLocal = new javax.swing.JTextField();
                jScrollPane1 = new javax.swing.JScrollPane();
                inputDescricao = new javax.swing.JTextArea();
                lblNome1 = new javax.swing.JLabel();
                inputDataInicio = new javax.swing.JTextField();
                lblNome2 = new javax.swing.JLabel();
                inputDataFim = new javax.swing.JTextField();
                lblNome3 = new javax.swing.JLabel();
                inputHoraInicio = new javax.swing.JTextField();
                lblNome4 = new javax.swing.JLabel();
                inputHoraFim = new javax.swing.JTextField();
                lblNome5 = new javax.swing.JLabel();
                inputNome5 = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblCriarAgenda.setText("Criar compromisso");

                lblNome.setText("Local");

                lblDescricao.setText("Descrição do compromisso:");

                btnCadastrar.setText("Cadastrar compromisso");
                btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCadastrarActionPerformed(evt);
                        }
                });

                btnVoltar.setText("Voltar");
                btnVoltar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnVoltarActionPerformed(evt);
                        }
                });

                inputDescricao.setColumns(20);
                inputDescricao.setRows(5);
                jScrollPane1.setViewportView(inputDescricao);

                lblNome1.setText("Data início");

                lblNome2.setText("Data Fim");

                lblNome3.setText("Hora início");

                lblNome4.setText("Hora fim");

                lblNome5.setText("Título");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                layout.createSequentialGroup()
                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                .addComponent(lblCriarAgenda)
                                                                                .addGap(148, 148, 148))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jScrollPane1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                388,
                                                                                                Short.MAX_VALUE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lblNome1)
                                                                                                                                .addGap(32, 32, 32)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(lblNome3)
                                                                                                                                                .addComponent(inputHoraInicio))
                                                                                                                                .addGap(58, 58, 58)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(lblNome2)
                                                                                                                                                .addComponent(inputDataFim))
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(lblNome4)
                                                                                                                                                .addComponent(inputHoraFim)))
                                                                                                                .addComponent(inputLocal)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout.createSequentialGroup()
                                                                                                                                                .addComponent(lblNome)
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                                                .addGap(6, 6, 6))
                                                                                .addComponent(inputNome5,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                false)
                                                                                                                .addComponent(inputDataInicio,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(btnVoltar,
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(btnCadastrar))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(lblDescricao)
                                                                                                                .addComponent(lblNome5))
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addContainerGap()));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblCriarAgenda)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(lblNome5)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(inputNome5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(16, 16, 16)
                                                                .addComponent(lblDescricao)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                97,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(lblNome4)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(inputHoraFim,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lblNome1)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(inputDataInicio,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(lblNome3)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(inputHoraInicio,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                .addComponent(lblNome2)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(inputDataFim,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblNome)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(inputLocal,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                52,
                                                                                Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(btnVoltar)
                                                                                .addComponent(btnCadastrar))
                                                                .addGap(21, 21, 21)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }// GEN-LAST:event_btnVoltarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        String titulo = this.inputNome5.getText();
        String descricao = this.inputDescricao.getText();
        String local = this.inputLocal.getText();
        String horaInicio = this.inputHoraInicio.getText();
        String horaFim = this.inputHoraFim.getText();
        String dataInicio = this.inputDataInicio.getText();
        String dataFim = this.inputDataFim.getText();

        if (titulo.isEmpty() || descricao.isEmpty() || local.isEmpty() || horaInicio.isEmpty()
                || horaFim.isEmpty()
                || dataInicio.isEmpty() || dataFim.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os dados obrigatórios.", "",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Compromisso comp = new Compromisso();

            comp.setTitulo(inputNome5.getText());
            comp.setDescricao(inputDescricao.getText());
            comp.setDataInicio(converterDataHora(inputDataInicio.getText() + " " + inputHoraInicio.getText()));
            comp.setDataFim(converterDataHora(inputDataFim.getText() + " " + inputHoraFim.getText()));
            comp.setLocal(inputLocal.getText());
            if (this.compromisso == null) {
                comp.setIdAgenda(agenda.getId());
                comp.setIdUsuario(usuario.getId());
                comp.setStatus(TipoStatus.ATIVO);

                CompromissoService.cadastrarCompromisso(comp);
            } else {
                CompromissoService.editarCompromisso(comp);
            }

            JOptionPane.showMessageDialog(null, "Compromisso " + (this.compromisso == null ? "cadastrado" : "editado") + " com sucesso!", "", JOptionPane.INFORMATION_MESSAGE);

            this.panel.buscarCompromissos();
            dispose();
        } catch (SQLException | IOException ex) {
            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar agenda.", "",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado ao cadastrar agenda.", "",
                    JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompromissoWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompromissoWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompromissoWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompromissoWindow.class.getName()).log(
                    java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompromissoWindow().setVisible(true);
            }
        });
    }

    private static Timestamp converterDataHora(String dataHora) {
        try {

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm");

            Date parsedDate = dateFormat.parse(dataHora);
            // Converte java.util.Date para java.sql.Timestamp
            return new Timestamp(parsedDate.getTime());
        } catch (ParseException e) {
            e.printStackTrace();
            return null;
        }
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCadastrar;
        private javax.swing.JButton btnVoltar;
        private javax.swing.JTextField inputDataFim;
        private javax.swing.JTextField inputDataInicio;
        private javax.swing.JTextArea inputDescricao;
        private javax.swing.JTextField inputHoraFim;
        private javax.swing.JTextField inputHoraInicio;
        private javax.swing.JTextField inputLocal;
        private javax.swing.JTextField inputNome5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lblCriarAgenda;
        private javax.swing.JLabel lblDescricao;
        private javax.swing.JLabel lblNome;
        private javax.swing.JLabel lblNome1;
        private javax.swing.JLabel lblNome2;
        private javax.swing.JLabel lblNome3;
        private javax.swing.JLabel lblNome4;
        private javax.swing.JLabel lblNome5;
        // End of variables declaration//GEN-END:variables
        private MaskFormatter mascaraData;
    private MaskFormatter mascaraHora;
}
