/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entities.Usuario;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import services.UsuarioService;

/**
 *
 * @author rebec
 */
public class UpdateUsuarioWindow extends javax.swing.JFrame {

    private Usuario usuario;
    private PanelWindow panel;

    /**
     * Creates new form RegisterWindow
     */
    public UpdateUsuarioWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public UpdateUsuarioWindow(Usuario usuario, PanelWindow panel) {
        initComponents();
        setLocationRelativeTo(null);
        this.usuario = usuario;
        this.panel = panel;

        this.inputEmail.setText(usuario.getEmail());
        this.inputNomeCompleto.setText(usuario.getNome());
        this.inputDataNascimento.setText(usuario.getDataNascimento().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        this.inputGenero.setSelectedItem(usuario.getStatus().name());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVoltar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblEditarUsuario = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblNomeCompleto = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        inputSenha = new javax.swing.JPasswordField();
        inputEmail = new javax.swing.JTextField();
        inputNomeCompleto = new javax.swing.JTextField();
        inputDataNascimento = new javax.swing.JFormattedTextField();
        inputGenero = new javax.swing.JComboBox<>();
        btnExcluirConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        lblEditarUsuario.setText("Editar usuário");

        lblEmail.setText("E-mail:");

        lblSenha.setText("Senha:");

        lblNomeCompleto.setText("Nome completo:");

        lblDataNascimento.setText("Data de nascimento:");

        lblGenero.setText("Gênero:");

        inputGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino", "Outros", "N/A" }));

        btnExcluirConta.setText("Excluir conta");
        btnExcluirConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirContaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGenero)
                            .addComponent(lblDataNascimento)
                            .addComponent(lblSenha)
                            .addComponent(lblNomeCompleto)
                            .addComponent(lblEmail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputSenha)
                            .addComponent(inputEmail)
                            .addComponent(inputNomeCompleto)
                            .addComponent(inputDataNascimento)
                            .addComponent(inputGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluirConta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblEditarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarUsuario)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(inputNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascimento)
                    .addComponent(inputDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnEditar))
                .addGap(18, 18, 18)
                .addComponent(btnExcluirConta)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String email = this.inputEmail.getText();
        String nomeCompleto = this.inputNomeCompleto.getText();
        String senha = this.inputSenha.getText();
        String dataNascimento = this.inputDataNascimento.getText();
        String genero = this.inputGenero.getSelectedItem().toString();

        if (email.isEmpty() || nomeCompleto.isEmpty()
                || dataNascimento.isEmpty() || genero.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os dados obrigatórios.", "", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Usuario usuario = this.usuario;

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate data = LocalDate.parse(dataNascimento, formatter);

            usuario.setNome(nomeCompleto);
            usuario.setEmail(email);
            usuario.setDataNascimento(data);
            usuario.setFoto("");
            usuario.setSenha(senha.isEmpty() ? usuario.getSenha() : senha);
            usuario.setGenero(genero);

            UsuarioService.editarUsuario(usuario);

            JOptionPane.showMessageDialog(null, "Usuário editado com sucesso", null, JOptionPane.INFORMATION_MESSAGE);

            this.panel.setUsuario(usuario);
            dispose();

        } catch (SQLException | IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro ao editar usuário", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirContaActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(null, "Deseja excluir sua conta?", "Excluir", JOptionPane.YES_NO_OPTION);

        if (confirmacao == 1) { //Não
            return;
        }

        try {
            UsuarioService.removerUsuario(usuario.getId());

            JOptionPane.showMessageDialog(null, "Usuário excluído com sucesso", null, JOptionPane.INFORMATION_MESSAGE);
            panel.dispose();
            dispose();

            LoginWindow frame = new LoginWindow();
            frame.setVisible(true);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(UpdateUsuarioWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUsuarioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUsuarioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUsuarioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUsuarioWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUsuarioWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluirConta;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JFormattedTextField inputDataNascimento;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JComboBox<String> inputGenero;
    private javax.swing.JTextField inputNomeCompleto;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEditarUsuario;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables
}
